// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flrnybizzmjhsdmyyiez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZscm55Yml6em1qaHNkbXl5aWV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MzU3NjIsImV4cCI6MjA2OTMxMTc2Mn0.aVaSG1X2N33iWQbUM6ZbXtgzn38A01xDFYFfbRpIqsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});